### ISSUE TITLE
Discussion: Orion blocking codegen requests

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/orion#138]
With the introduction of auth system in Orion we now have to provide session cookie for anonymous users to perform basic actions, but the problem is that graphql codegen tool needs access to download schema straight to IDE and it doesn't auth itself in the way we require. 

Three solutions I see right now are:
- Adjust Orion (I believe that we can unblock `__schema` entity or add some dev header that would allow to query Orion - this will require some work on Atlas - see last solution)
- Change codegen approach in Atlas (switch from downloading schema JSON to manually importing `schema.graphql`
- Find a solution in Atlas that would allow devs to insert their own session cookie into codegen request.

 Share your ideas :)

@Lezek123 @attemka @drillprop

**Comment by attemka** [comment]
I think its a good idea to check if we can achieve first solution, as it will be the easier one from the operators perspective. I believe that the operator should be able to install and run Atlas without creating an Orion account. cc @ignazio-bovo
