### ISSUE TITLE
migration issue "bid" is not a table or foreign table

### ISSUE THREAD

**Issue by traumschule** [Joystream/orion#150]
I was notified that orion2 had stopped syncing and reran `make prepare && make up` today.
It was upgraded and fully synced from scratch last friday: branch master 6f3c654dd64dfa4d4539a8456e16d3415dd7d4b7

Now container `node:16` shows a migration issue:
![bidissue](https://github.com/Joystream/orion/assets/31551045/fbe42cd4-7e14-49ad-97f7-fc5ea232e178)
> diverError: error: "bid" is not a table or foreign table

Please assist.

**Comment by ignazio-bovo** [comment]
I believe this was resolved, by regenerating the `db/migrations/*-Data.js`
