### ISSUE TITLE
 Relevancy scopre adjustment to include custom channels boosting and downgrading in relevancy

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/orion#213]
## Context
We'd like to be able to control which channels are showing further up in the homepage. Suggestion to update Orion relevancy formula to be able to boost the relevancy score for individual channels as well as demote some other channels in the ranking of homepage.

Current formula

`Forumula: R = (N * -A) + (B * views_num) + (C * comments_num) + (D * reactions_num)`
`N = (E * days_since_published_on_gleev + F * days_since_published_on_yt) / (E + F)`

```
    newnessWeight: A,
    viewsWeight: B,
    commentsWeight: C,
    reactionsWeight: D,
    joysteamTimestampSubWeight: E,
    ytTimestampSubWeight: F
```

Suggested new formula
`R = ((N * -A) + (B * views_num) + (C * comments_num) + (D * reactions_num))*CW`
👉 Where CW= channel Weight, float
when CW <1, this would decrease channel score
when CW>1, this would increase channel score

## Scope
- [ ] Introduce a new field for channels which can be incorporated to the relevancy formula calculation as stated above
- [ ] Update relevancy formula to include custom channel booster CW
- [ ] The value of such field (aka `CW`) should be manipulatable via Orion mutation for multiple channels at once

### Dependencies
⚠️ Blocked by 
- #218 

### Operational implications
Each week after the payout stats is prepared by Content WG lead the set of channels that are marked with 
Silver, Gold and Diamond tiers will need to be manually adjusted via Orion mutation. 
Suggested trial values: Silver 1.25; Gold 1.5; Diamond 2
(Bronze channels will not have this param, which is equal to having it set to `1`)

This approach also allows to boost individual channel ranking to any value. E.g. if set to <1 content of such channel would be shown below all the new content from Bronze channels.

ℹ️ NB: the actual values would need to be calibrated with the newness parameter in the formula above so that content from higher tiers that is 30 days and older gets displayed below newer videos from lower tiers.

**Comment by dmtrjsg** [comment]
+ incorporate YT BE tiers
+ reduce views/ reactions/ comments in the forumla

**Comment by dmtrjsg** [comment]
Depends
- https://github.com/Joystream/orion/issues/218

**Comment by bedeho** [comment]
Just to be totally clear that I'm understanding, for each video, we are trying to maintain the following value

`(E * days_since_published_on_gleev + F * days_since_published_on_yt) * CW / (E + F)`, where 

`E` and `F` are fixed positive integers, and  `CW` is a positive floating number specific to each channel update by moderators. The homepage is then just showing all videos which are int he crypto category, ranked by this number in descending order. Is all of this accurate? I don't think so, but this is my best suggestion.

Either way, please add this to Notion page for Gleev somewhere, including current values of these global constant.

**Comment by dmtrjsg** [comment]
@bedeho 
>  Is all of this accurate?

Sorry that was not entirely correct at the time of writing: 

`Forumula: R = (N * -A) + (B * views_num) + (C * comments_num) + (D * reactions_num)`
`N = (E * days_since_published_on_gleev + F * days_since_published_on_yt) / (E + F)`

All of the variables in this formula are weights, and all are floats. 

```
    newnessWeight: A,
    viewsWeight: B,
    commentsWeight: C,
    reactionsWeight: D,
    joysteamTimestampSubWeight: E,
    ytTimestampSubWeight: F
```

Suggested new formula
`R = ((N * -A) + (B * views_num) + (C * comments_num) + (D * reactions_num))*CW`

 CW is a positive floating number specific to each channel update by moderators. The homepage is then just showing all videos which are int he crypto category, ranked by this number in descending order.
 
 The above is [added to Notion>](https://www.notion.so/joystream/Homepage-feed-mgt-26cd9aaae43f4a6ca49af06da4bb0a88?pvs=4)

**Comment by bedeho** [comment]
- Boosting channels additively seems to me to be a simpler way to allow simple and direct control of how different channels are ordered. Perhaps the term "weight" caused some confusion, bias may be more apprioriate, but apart from the name, it just seems more straight forward to reason about in order to ensure certain changes in the final ordering, which is what curators will want to do.
- It seems to me that having to update `N` every day for every video is a lot of work, but we have to do it for `N` to be correct, because we have no guarantee that any of the other triggers to update `R` will happen for all videos from one day to the next. The result is that videos published long ago, which have no views, comments, reactions, will have a small `N` and get ranked highly. I assume this is already occurring. 

Why not just compute the score for each video on demand? Are we sure this is really that expensive? This also means we can drop the extra code we are running now to detect if `R` needs to be recomputed. So we just do this as the homepage query

```sql
SELECT
  id,
  ...
  TIMESTAMPDIFF(HOUR, created, NOW()) AS hours_difference
  (hours_difference*AGE_WEIGHT +  channel_bias*CHANNEL_WEIGHT) AS rank
FROM
  videos
ORDER BY
  rank DESC;
```

Where `AGE_WEIGHT` and `CHANNEL_WEIGHT` are global weights that capture how newness vs quality should be traded off, linearly, and `channel_bias` is just channel specific bias, which is also positive. The primary cost increase comes from need to join with channel table, to grab `channel_bias`, but do we know that this is actually all that expensive? If it is, it seems next best thing is just to replicate `channel_bias` in videos, as that does not change from one moment to the next as time progresses, unlike `N`.

**Comment by dmtrjsg** [comment]
I'm out of my depth to comment on the impact of page load speed based on the suggested approach, just adding my comments: 

1. The current N is a balanced value between age of video on Gleev and Youtube which is controllable.
2. Current R formula also has engagement built in to it, which we may want to bring back at some point to allow for "natural selection". 
3. If the suggested approach impacts video load speed by >1second I think it may not be worth it. I've always been under impression that the goal is to make FE as thin as possible in pursuit of performance.

**Comment by bedeho** [comment]
> The current N is a balanced value between age of video on Gleev and Youtube which is controllable.

Yes, but this can be accomodated in the approach above also. Just doing `min(youtube, gleev)` seems sufficient to pick oldest date.

> Current R formula also has engagement built in to it, which we may want to bring back at some point to allow for "natural selection".

Yeah I'm not sold on any of that for now, given how gameable it is withour small audience, looking at recommendations and how it treats that in an integrated way seems like the best next step.

> If the suggested approach impacts video load speed by >1second I think it may not be worth it. I've always been under impression that the goal is to make FE as thin as possible in pursuit of performance.

If so, then we need a way to treat newness that does not go stale by default for virtually all videos. This would then likely have to include some sort of process that goes through and regularly recomputes a total rank bias, for all videos more or less continously, not waiting to be triggered by any event.

**Comment by dmtrjsg** [comment]
@bedeho 
> then we need a way to treat newness that does not go stale by default for virtually all videos

Just an observation: the most frequent recalc of `R` was connected to user engagement events. Newness itself is working with `days since published` so it is sufficient to do it only once every 24hrs. 

It is even less frequenty required for the channels `bias` multiplicator, as my expectation that non-default bias values will be added in-line with reporting, so once per week is most likely.
