### ISSUE TITLE
videosConnection and videos queries are getting slower from the after\cursor incrementation

### ISSUE THREAD

**Issue by attemka** [Joystream/orion#227]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVduQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d981107ab41ea94cb6d834ccada21cb2a4e6a474/Screenshot%202023-11-06%20at%2016.21.02.png)
Screenshot was taken from the debug session. Query is the same as on the Atlas homepage.
offset values tested:
```
1
10
100
1000
10000
100000
300000
```

with the times increasing linear (see screenshot)

same will happen with setting the cursor (after) for the `videosConnection` query

ER: cursor\skip doesn't affect query execution time

**Comment by WRadoslaw** [comment]
Unfortunately, the current cursor behavior available for us by Subsquid is based on the `offset` and `limit` which will have decrementing performance as it grows. There is no easy fix for this on the Orion side, on the Atlas side I managed to decrease load time and increase stability by removing a lot of data from basic video fragment. https://github.com/Joystream/atlas/pull/5285

**Comment by ignazio-bovo** [comment]
I don't think that querying the `public` schema vs the `admin` schema is the culprit here. 
See https://dba.stackexchange.com/a/298041
`OFFSET m` has complexity of O(m) even with `ORDER_BY indexed_column` Hence on `LIMIT 10 OFFSET n - 10` the complexity is O(n) and not constant
