### ISSUE TITLE
Create a processor health check in checkly

### ISSUE THREAD

**Issue by attemka** [Joystream/orion#249]
Currently there are no notifications if processor has failed.
It will be good to query the `lastCompleteBlock` field and send the notification if the number is the same for 2 consecutive calls.
AFAIK, you can't compare a new result to a previous one, but there is a teardown script in checkly, so we can estimate a block number there and throw an error if it differs significantly (e.g for more than 20 blocks)

**Comment by ignazio-bovo** [comment]
This is part of the 30 days sprint and I am currently considering checkly heartbeats https://www.checklyhq.com/blog/heartbeat-monitoring-with-checkly/

**Comment by WRadoslaw** [comment]
Done without code changes
