### ISSUE TITLE
Draft: Orion v2 Requirements

### ISSUE THREAD

**Issue by bedeho** [Joystream/orion#45]
# Terminology

Currently, Orion is a single node backend service which does three things for  `Atlas` in a given instance of this app, i.e. not across all instances of this app, or certainly all consumer apps that may exist:

1. Follower count on each channel
2. Consumption data for all channels and videos, i.e. how many views
3. Provides a unified `GraphQL` API that stitches together an underlying query node for on-chain data and the data mentioned in 1 & 2, so that you for example can in a simple (but not very performant) way simultaneously get all videos and their corresponding view counts.
4. Holds featured content indexes.
5. Captures content reporting from users.

In this document, the term `Orion` should be understood more broadly. It should be understood to be all of the backend infrastructure owned by a gateway operator and powering a single app instance. This may end up involving a range of different services and nodes in the end.

# Requirements

## The Big Vision

Here I try to list the panoply of benefits we would like `Orion` to bring to `Atlas` and content consumption application developers and operators over the long term. It's useful to outline this vision now, so as to

- **Unified/Ergonomic/Performant API:** The current stitching in v1 cannot do this well, because it fundamentally just relays all on-chain data queries to a QN node, so query speed becomes too low when fetching across on-chain and off-chain state. Unlocking this requires some unified state which can be efficiently queried on one machine, or sharded in a systematic way. The programmatic schemas generated from the data models in Hydra/Subsquid will just never be _excellent_, there will always be tons of missing edge cases which makes clients complex. In a sense, the client side library for this API may just end up being the canonical Joystream SDK.
- **User accounts:** There are a lot of value added features which depends on the server side having some representation of the user. By user accounts one means some stable representation, subject to authentication of _some kind_, with an immutable identifier. Probably has to start as a very light weight entity, e.g. for a fresh user hitting the site needing to auth with `Argus` to play back content, that can graduate through different stages, e.g. first to email based auth, to then connecting full membership.
- **Email auth:** (requires user accounts) Allowing use of some features without having to install a external wallet/signer will be huge for reducing onboarding friction. This does not need to include on-chain features per say, just having a stable account over time which persist across sessions.
- **Non-external wallet:** (requires user accounts & email auth) Removing the _need_ for consumers, and even creators, to start using applications, and even on-chain features, without having to install and configure a wallet, would be huge for reducing onboarding friction. This could either be a fully hosted type of wallet, or some sort of ephemeral client side wallet, e.g. Audius does this I think.
- **Private server-side state:** (requires user accounts & email auth) There is lots of very valuable _private_ data useful to each user, such as who they follow, viewing history, notifications that have been viewed etc. But also more infrastructure level state about how interactions with the storage system or blockchain are evolving. Having this information server side means that you avoid problems that emerge from having this client side, and then either having multiple tabs open in the browser, or multiple devices/browsers which are not synchronized.
- **Store and relay consumption data:** (requires user accounts) Knowing who watched what content at what time is both very valuable for powering recommendations within each app, but also critical information to relay to some shared data repository that can power creator payouts and analytics. It has not yet been determined how this data will be shared and unified across gateways and with the council, however simply starting with collecting it is very useful.
- **Store and relay infrastructure error Data:** (requires user accounts) A key determinant of the UX will be how low latency and reliable the streaming and playback of content will be. There can be lots of different errors or performance degradation, and having operators collect data on this, and later relay to DAO, will be very useful as an input to the operational activities of the storage and bandwidth lead.
- **Argus authentication:** (requires user accounts & apps as first class citizens) Its key that Argus soon starts gating access to genuine app users, so parasitic uses of the DAO resources do not emerge, and it is also critical in order for the infrastructure to do proper accounting of how much is consumed of various kinds of content across distinct apps, so as to report to the DAO.
- **Email Notifications:** (requires user accounts & email auth) Being able to push certain notifications to the inbox of users is a key user retention feature, and would be valuable for both consumers and creators in innumerable ways, e.g. on comments, likes, auction settlement, payouts, revenue splits, you name it.
- **Search:** Proper full-text search across videos, channels and within channels and categories. Current Hydra search is totally broken.
- **Category Filtering:** Currently, `Atlas` has built in client side filtering relating to display categories, but having this automatically included in all queries avoids any possibility of leakage, and also allowing tuning of this without having to rebuild Atlas or Orion, would be great.
- **Operator Filtering:** A scaleable way for operators to omit channels and videos wholesale is critical, e.g. for DMCA compliance purposes, right now this does not work at any sort of scale.
- **Customisable Recommendations:** Being able to provide content for home feed, next video, related videos, powered by operator specific recommendation engines, would be a game changer. Our default engine would probably be [Tensorflow Recommenders](https://github.com/Joystream/orion/issues/43).
- **Upload Intermediation:** (requires user accounts) Heavy assets will require transcoding, image extraction, defensive filtering and lots of other possible enhancements that may be app specific. This needs to be done based on raw data from user, and then doing upload step to infrastructure, which also has the benefit of allowing user to close app once initial upload has happened, but processing is not done yet.

## Puzzle

In this kind of model, how much room can we make for people to customise things deeply, say because they are introducing totally new kinds of metadata and so on (e.g. downvotes for comments), which does not require someone to fork all of Orion and eventually ending up in a tricky maintenance conundrum as upstream changes keep getting published.

## First Step: Orion V2

For the very first release, which we call V2, let's settle on the following narrower, but still very high value scope, which can be released without changes to Atlas which are too costly (hopefully!).

1. **Unified/Ergonomic/Performant API:** Importantly, this API is hand-crafted, no more of the programmatic QN API, but the path of least resistance is to just copy the form currently expected by Atlas, with the exception of adding decorations which currently are making Atlas complex because Hydra is missing various kinds of filtering. Asking Atlas team for a list would probably be best way to go about it, and looking at their code base is probably also useful. See this issue for a suggestion for how to deal with backend state, but ultimately it's up to the designer to conclude: https://github.com/Joystream/orion/issues/30#issuecomment-1295766043
2. **Operator Filtering:** Probably should be exposed through a dedicated operator API that can grow over time, and power both WebUIs and CLIs as people chose to build tooling on top.
3. **Search:** Hopefully comes out of the box cheap with suitable selected backend which is properly configured.
4. **Featuring:** This has to be maintained as a feature that is still needed, but should be possible without pausing/rebuilding.

All APIs should be GraphQL, node still in Typescript. Make sure to start versioning & change-log from the get-go, and having some public utility endpoints relating to what version the node is, what block it currently has processed, etc., could be useful. Writing some initial documentation on architecture and approach can be a good way to encourage us to have it well documented continously, as the burden of doing it later may become really big once the system gets more complex.

_Note: I am not convinced content reporting really belongs in there, as its quite orthogonal to everything else, as it currently works, but I also recognize that its quite convenient to have everything come as one easy package now in the beginning._

**Comment by kdembler** [comment]
Just to be on the same page, currently Orion does a bit more than the 3 points you've mentioned. It also does content reporting and content featuring, you can read more here: https://github.com/Joystream/orion#functionalities-overview

Other than that, looks really solid. Can't wait for this to happen!
