### ISSUE TITLE
Orion v2: Cannot get featured videos without `x-operator-secret` and `x-display-hidden-entities` header

### ISSUE THREAD

**Issue by drillprop** [Joystream/orion#91]
Featured videos should be public. Currently with query 
```
query featured {
  videoFeaturedInCategories {
    id
    video {
      isExcluded
      id
    }
  }
}

``` 
I'm getting `message": "Cannot return null for non-nullable field VideoFeaturedInCategory.video.",`

Strangely, If I remove `video` or I add `x-operator-secret` and `x-display-hidden-entities` headers the query works

**Comment by Lezek123** [comment]
Fixed in: https://github.com/Joystream/orion/pull/49/commits/8808650d7ecee9a13487668ffd46ca7e59e16cb0
