### ISSUE TITLE
Info related about APP_PRIVATE_KEY missing from docs

### ISSUE THREAD

**Issue by freakstatic** [Joystream/orion#97]
If one doesn't define the APP_PRIVATE_KEY the following error is displayed when running the orion docker container

```
Error: Required env variable "APP_PRIVATE_KEY" is missing from the environment
    at loadEnvVar (/usr/src/orion/dist/config.js:22:11)
    at Config.loadConfig (/usr/src/orion/dist/config.js:64:31)
    at main (/usr/src/orion/dist/main.js:11:22)
    at /usr/src/orion/dist/main.js:40:5
```

It seems that the information about this enviroment variable is missing from the "[deployment docs](https://github.com/Joystream/orion#deployment)"

**Comment by traumschule** [comment]
That's probably already on the list, the new guide is WIP: https://github.com/Joystream/orion/blob/master/docs/operator-guide.md
